server:
  port: 8084


spring:
  application:
    name: timeseries-database-service
  influx:
    token: my-super-secret-auth-token
    bucket: nais_bucket
    org: nais_org
    url: http://localhost:8086
    user: nais
    password: password
  data:
    redis:
      host: timeseries-redis
      port: 6380

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
