apiVersion: 1

datasources:
  - name: LibraryAPI
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    jsonData:
      # Base URL biblioteckog servisa (dostupan unutar Docker mreze)
      base_url: "http://library-service:9060"
    version: 1
    editable: true
