apiVersion: 1

datasources:
  - name: TimeseriesAPI
    uid: timeseries-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    jsonData:
      base_url: "http://timeseries-service:8084"
    version: 1
    editable: true
