"""Books ingestion.

Idempotent: no-op if the collection already holds >= BOOKS_MIN_ROWS rows.
Data sources (in priority order):
    1. Parquet file at DATA_PATH  (columns from prepare_book_and_review_data.py:
                                                                    goodreads_id, isbn, title, author, description,
                                                                    language, coverImg, publisher, pages, has_image)
         Legacy files with genre/year/keywords are also supported.
  2. Synthetic generation via Faker (fallback, no network required)

Synthetic-document strategy
---------------------------
The same string is stored in two places per book:
  synthetic_document → BM25 sparse vector (auto-generated by Milvus function)
  dense_embedding    → MiniLM cosine ANN vector

This mirrors the design in books_service.py so ingest and runtime produce
identical text representations.
"""

import argparse
import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import BATCH_SIZE, BOOKS_COLLECTION, BOOKS_MIN_ROWS
from schema.books_schema import books_index_params, books_schema
from services.milvus_service import milvus_service
from services.minilm_embedding_service import minilm_service

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-8s %(message)s")
logger = logging.getLogger(__name__)

_ROOT     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(_ROOT, "data", "books.parquet")

_GENRES = [
    "Fiction", "Non-Fiction", "Science Fiction", "Fantasy", "Mystery",
    "Thriller", "Romance", "Historical Fiction", "Biography", "Self-Help",
    "Science", "Philosophy", "Poetry", "Horror", "Adventure",
]
_LANGUAGES = ["English", "French", "German", "Spanish", "Italian", "Russian"]
_THEMES = [
    "love and loss", "courage and sacrifice", "identity and belonging",
    "power and corruption", "hope and redemption", "truth and deception",
    "friendship and betrayal", "justice and revenge", "freedom and oppression",
]
_DESC_TEMPLATES = [
    "A gripping tale of {theme} that explores the depths of human nature.",
    "An insightful exploration of {theme} with vivid characters and a compelling narrative.",
    "A masterful work delving into {theme} that challenges readers to think differently.",
    "A sweeping story of {theme} set against a richly detailed historical backdrop.",
    "A thought-provoking examination of {theme} that resonates long after the last page.",
]


# ── helpers ──────────────────────────────────────────────────────────────────

def _clean(text: str, max_bytes: int) -> str:
    """Truncate so the UTF-8 byte length stays within max_bytes."""
    encoded = text.strip().encode("utf-8")
    if len(encoded) <= max_bytes:
        return text.strip()
    return encoded[:max_bytes].decode("utf-8", errors="ignore")


def _to_int(value, default: int = 0) -> int:
    try:
        if value is None:
            return default
        return int(value)
    except (TypeError, ValueError):
        return default


def _build_synthetic_document(r: dict) -> str:
    """Single text fed to both BM25 function and MiniLM encoder."""
    return (
        f"Goodreads ID: {r.get('goodreads_id', '')}. "
        f"Title: {r.get('title', '')}. "
        f"Author: {r.get('author', '')}. "
        f"Pages: {r.get('pages', '')}. "
        f"Genre: {r.get('genre', '')}. "
        f"Publisher: {r.get('publisher', '')}. "
        f"Year: {r.get('year', '')}. "
        f"Language: {r.get('language', '')}. "
        f"Description: {r.get('description', '')}. "
        f"Keywords: {r.get('keywords_text', '')}."
    )[:6000]


# ── collection lifecycle ──────────────────────────────────────────────────────

def _has_bm25_schema(client) -> bool:
    """Return True if the existing collection already has the BM25 sparse field."""
    try:
        info       = client.describe_collection(BOOKS_COLLECTION)
        field_names = [f["name"] for f in info.get("fields", [])]
        return "sparse" in field_names
    except Exception:
        return False


def _prepare_collection(reset: bool) -> None:
    client = milvus_service.client

    if client.has_collection(BOOKS_COLLECTION):
        if reset:
            client.drop_collection(BOOKS_COLLECTION)
            logger.info("Dropped collection '%s' (--reset).", BOOKS_COLLECTION)
        elif not _has_bm25_schema(client):
            client.drop_collection(BOOKS_COLLECTION)
            logger.info(
                "Dropped '%s' — outdated schema (no BM25 sparse field), recreating.",
                BOOKS_COLLECTION,
            )

    if not client.has_collection(BOOKS_COLLECTION):
        client.create_collection(
            collection_name=BOOKS_COLLECTION,
            schema=books_schema(client),
            index_params=books_index_params(client),
            consistency_level="Strong",
        )
        logger.info("Created collection '%s'.", BOOKS_COLLECTION)

    milvus_service.load_collection(BOOKS_COLLECTION)


def _already_ingested() -> bool:
    stats = milvus_service.client.get_collection_stats(BOOKS_COLLECTION)
    count = int(stats.get("row_count", 0))
    if count >= BOOKS_MIN_ROWS:
        logger.info(
            "Collection '%s' already has %d rows — skipping.",
            BOOKS_COLLECTION, count,
        )
        return True
    return False


# ── flush helper ─────────────────────────────────────────────────────────────

def _flush(batch: list[dict], total: int) -> int:
    """Encode synthetic_document → dense_embedding and insert the batch."""
    synth_docs = [r["synthetic_document"] for r in batch]
    embeddings = minilm_service.encode(synth_docs)
    records    = [{**r, "dense_embedding": emb} for r, emb in zip(batch, embeddings)]
    milvus_service.insert(BOOKS_COLLECTION, records)
    total += len(records)
    logger.info("  %d rows inserted ...", total)
    return total


# ── data sources ──────────────────────────────────────────────────────────────

def ingest_from_parquet(data_path: str) -> None:
    try:
        import pyarrow.parquet as pq
    except ImportError:
        logger.error("pyarrow is not installed.  Run: pip install pyarrow")
        sys.exit(1)

    logger.info("Loading books from %s ...", data_path)
    rows = pq.read_table(data_path).to_pylist()
    logger.info("Loaded %d rows from parquet.", len(rows))

    batch, total = [], 0
    for i, row in enumerate(rows):
        kw = row.get("keywords_text") or row.get("keywords") or ""
        if isinstance(kw, list):
            kw = ", ".join(str(k) for k in kw)

        has_image = row.get("has_image")
        if has_image is None:
            has_image = bool(row.get("coverImg"))

        record = {
            "goodreads_id":  _clean(str(row.get("goodreads_id") or ""), 32),
            "isbn":          _clean(str(row.get("isbn") or f"ISBNX{i:09d}"), 32),
            "title":         _clean(str(row.get("title")     or "Unknown Title"),    512),
            "author":        _clean(str(row.get("author")    or "Unknown Author"),   256),
            "coverImg":      _clean(str(row.get("coverImg")  or ""),              2048),
            "pages":         _to_int(row.get("pages"), default=0),
            "has_image":     bool(has_image),
            "genre":         _clean(str(row.get("genre")     or "General"),          128),
            "publisher":     _clean(str(row.get("publisher") or "Unknown Publisher"), 256),
            "year":          _to_int(row.get("year"), default=2000),
            "language":      _clean(str(row.get("language")  or "English"),           32),
            "description":   _clean(str(row.get("description") or ""),              4000),
            "keywords_text": _clean(str(kw),                                        1024),
        }
        record["synthetic_document"] = _build_synthetic_document(record)
        batch.append(record)

        if len(batch) >= BATCH_SIZE:
            total = _flush(batch, total)
            batch = []

    if batch:
        total = _flush(batch, total)

    logger.info("Done — %d books in '%s'.", total, BOOKS_COLLECTION)


def ingest_from_faker(limit: int) -> None:
    """Generate ``limit`` synthetic books deterministically via Faker."""
    try:
        from faker import Faker
    except ImportError:
        logger.error("faker is not installed.  Run: pip install faker")
        sys.exit(1)

    fake = Faker()
    Faker.seed(42)

    logger.info("Generating %d synthetic books with Faker ...", limit)
    batch, total = [], 0

    for _ in range(limit):
        genre    = fake.random_element(_GENRES)
        language = fake.random_element(_LANGUAGES)
        year     = fake.random_int(min=1900, max=2024)
        theme    = fake.random_element(_THEMES)
        desc     = fake.random_element(_DESC_TEMPLATES).format(theme=theme)

        # Plausible ISBN-13 (check digit not validated — good enough for seeding)
        isbn = "978" + "".join(str(fake.random_digit()) for _ in range(10))

        kw_list      = [genre.lower(), language.lower(), fake.word(), fake.word(), str(year)]
        keywords_text = ", ".join(kw_list)

        record = {
            "goodreads_id":  "",
            "isbn":          isbn[:32],
            "title":         fake.catch_phrase()[:512],
            "author":        fake.name()[:256],
            "coverImg":      "",
            "pages":         0,
            "has_image":     False,
            "genre":         genre[:128],
            "publisher":     (fake.company() + " Press")[:256],
            "year":          year,
            "language":      language[:32],
            "description":   desc[:4000],
            "keywords_text": keywords_text[:1024],
        }
        record["synthetic_document"] = _build_synthetic_document(record)
        batch.append(record)

        if len(batch) >= BATCH_SIZE:
            total = _flush(batch, total)
            batch = []

    if batch:
        total = _flush(batch, total)

    logger.info("Done — %d books in '%s'.", total, BOOKS_COLLECTION)


# ── entry point ───────────────────────────────────────────────────────────────

def ingest(data_path: str = DATA_PATH, reset: bool = False, limit: int = BOOKS_MIN_ROWS) -> None:
    _prepare_collection(reset)
    if _already_ingested():
        return

    if os.path.exists(data_path):
        ingest_from_parquet(data_path)
    else:
        logger.info(
            "Parquet not found at %s — falling back to Faker synthetic generation.",
            data_path,
        )
        ingest_from_faker(limit)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ingest books into Milvus")
    parser.add_argument("--data",  default=DATA_PATH,       help="Path to books.parquet")
    parser.add_argument("--reset", action="store_true",      help="Drop and recreate collection")
    parser.add_argument("--limit", type=int, default=BOOKS_MIN_ROWS,
                        help="Number of synthetic books when parquet is absent")
    args = parser.parse_args()
    ingest(args.data, args.reset, args.limit)